# Path to the reference genome.
REFERENCE: 'data/ref/hsa.hg19.fa'

# Path to the sample reads.
NORMAL: 'w1/SLX-10378.s_1.r_1.org.bam'
TUMOUR: 'w1/SLX-10378.s_1.r_1.mutant.bam'

# Path to the mutation file.
MUTATIONS: 'w1/mutations.txt'

# Selected variant caller
CALLER: 'somaticsniper'

# Directory where intermediate files will be written.
OUT_DIR: 'w2'

# Number of cores to run on
NTHREADS: 64
