# Directory where the VCF files are
VCF_DIR: 'p3'

# Directory where intermediate files will be written.
OUT_DIR: 'p4'

# Variance caller (vardict, somaticsniper, mutect)
CALLER: 'vardict'

# Number of mutations to validate
NMUTATIONS: 20

# Number of cores to run on
NTHREADS: 64
