# Directory where the VCF files are
VCF_DIR: 'run1_p2'

# Directory where intermediate files will be written.
OUT_DIR: 'run1_p4_somaticsniper'

# Variance caller (vardict, somaticsniper, mutect)
CALLER: 'somaticsniper'

# Number of mutations to validate
NMUTATIONS: 20

# Number of cores to run on
NTHREADS: 64
