# Path to the reference genome.
REFERENCE: 'data/ref/hsa.hg19.fa'

# Path to the sample reads.
NORMAL: 'p1/SLX-10378.s_1.r_1.normal.bam'
TUMOUR: 'p1/SLX-10378.s_1.r_1.tumour.bam'

# Directory where intermediate files will be written.
OUT_DIR: 'p3'

# Variance caller (vardict, somaticsniper, mutect)
CALLER: 'somaticsniper'

# Number of cores to run on
NTHREADS: 64
