# Path to the reference genome.
REFERENCE: 'data/ref/hsa.hg19.fa'

# Path to the sample reads.
NORMAL: 'run1_p3/SLX-10378.s_1.r_1.normal.bam'
TUMOUR: 'run1_p3/SLX-10378.s_1.r_1.tumour.bam'

# Directory where intermediate files will be written.
OUT_DIR: 'run1_p3_vardict'

# Variance caller (vardict, somaticsniper, mutect)
CALLER: 'vardict'

# Number of cores to run on
NTHREADS: 64
